### ISSUE TITLE
RAM_Toolkit: Read overlapping panels

### ISSUE THREAD

**Issue by JosefTaylor** [BHoM/RAM_Toolkit#93] opened 2019-09-13 15:40 UTC
### Description:
Overlapping panels, such as thickening pads on floors, come in with double the number of edges they should have.

### Test Script:
https://burohappold.sharepoint.com/:f:/s/BHoM/ErMIsKCSh19FuXi_LXOHY0cB2ztigJzrPguTz4cjXXkbSw?e=84EG8G

**Comment by enarhi** [comment] 2019-12-23 23:59
@JosefTaylor is this still occurring with the latest build? As far I can tell it is not, but want to confirm before closing the issue. Looks like no duplicate edges come through, we do get the thickened region inclusive to the surrounding floor but that is expected behavior.

**Closed** 2020-03-16 15:18 UTC
Labels: type:bug
